version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore NPM Package Cache
      key: dependency-cache-{{ checksum "yarn.lock" }}

  install_dependencies: &install_dependencies
    run:
      name: Install dependencies
      command: yarn

  save_cache: &save_cache
    save_cache:
      name: Save NPM Package Cache
      key: dependency-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules

jobs:
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: check-yarn
          command: yarn -v
      - <<: *restore_cache
      - <<: *install_dependencies
      - <<: *save_cache
      - run:
          name: Test
          command: yarn test

  build:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_dependencies
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - build

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *restore_cache
      - <<: *install_dependencies
      - run:
          name: Install netlify-cli
          command: sudo yarn global add --silent netlify-cli
      - run:
          name: Deploy to Netlify
          command: 'netlify deploy --dir=./build -p -m "Deployment from CircleCI build #$CIRCLE_BUILD_NUM"'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
